apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aiplatform
  region: eu-west-1

managedNodeGroups:
- name: nodegroup
  labels: { role: workers }
  desiredCapacity: 4
  instanceType: m5.xlarge
  iam:
    withAddonPolicies:
      albIngress: true